version: "3"
services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123
            - POSTGRES_DB=defipools
        ports:
            - "5432:5432"
        volumes:
            - ./db-data:/var/lib/postgresql/data
        networks:
            - pg-net
    redis:
        image: redis:latest
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis
        networks:
            - redis-net
        ports:
            - 6379:6379
        volumes:
            - ./redis-data:/data
networks: 
    pg-net:
    redis-net:
volumes:
    db-data:
    redis-data: